### ISSUE TITLE
App does not launch on Mojave 10.14.2

### ISSUE THREAD

**Issue by tsouchlarakis** [nathanbirrell/overcast-macos#10]
The app does not open on macOS Mojave 10.14.2. The prompt comes up letting the user know that the app is from an unidentified developer, but then proceeds not to launch.

**Comment by nathanbirrell** [comment]
PRs welcome mate, unfortunately I haven't been using this app lately, just been sticking to the official iOS.

**Comment by tsouchlarakis** [comment]
No problem, thank you for following up. We are lucky the iOS app is so great by itself! I will close this issue.
