### ISSUE TITLE
Sign In With Apple ID

### ISSUE THREAD

**Issue by kennyjeffris** [nathanbirrell/overcast-macos#17]
Can't sign in with Apple ID on Big Sur.  Button greys out and nothing happens.

**Comment by nathanbirrell** [comment]
Hey @kennyjeffris this is no longer maintained unfortunately. I believe Marco said all M1 Macs will have support for Overcast (via iOS port) but unsure that Intel Macs will get the same treatment.

https://twitter.com/marcoarment/status/1328414533782794241
