### ISSUE TITLE
Could you clarify that this is unofficial?

### ISSUE THREAD

**Issue by marcoarment** [nathanbirrell/overcast-macos#2]
I appreciate the effort, and I hope people find this useful.

But would you mind clarifying in the site and GitHub README that this is an *unofficial* app wrapper around the Overcast web interface, not actually Overcast for Mac?

I've had a number of people asking me about this already, and it's important that nobody gets confused into thinking this is officially supported, endorsed, or written by Overcast.

Thanks.

**Comment by nathanbirrell** [comment]
Absolutely, done [here](https://github.com/nathanbirrell/overcast-macos/commit/14c7117640be58be70dbcbc858111d29796826f3). Sorry for not making that explicit @marcoarment.

**Comment by nathanbirrell** [comment]
And again [here](https://github.com/nathanbirrell/overcast-macos/commit/7e9a7953948e4fce09e672b0c4646b9140140f56) 👍
