### ISSUE TITLE
Newest first and more

### ISSUE THREAD

**Issue by maanemann** [nathanbirrell/overcast-macos#5]
Hi. Nice, simple app you've made, thanks for that!

I realise that the design mostly mirrors the website, and that puts a limit to how much it can be customised. But idk, I'm not a programmer, so I'll just go ahead and express my suggestion:

In the iOS app I have an "All Episodes" playlist (I think it's default), which puts the newest episodes first, and that's how I like my podcasts to be sorted. Would it be possible to do this in your Mac OS app? The coolest way would be to make a playlist feature with sorting options, preferably one that syncs with iOS, but not necessarily. Otherwise there could just be a little drop-down menu with sorting options, or, even simpler, a switch that reverses the order (as right now the oldest are displayed first).

In the iOS app you can also rearrange the episodes by dragging, which would be cool as well, but probably more complicated, I guess. This feature is nice, because the episodes list also works as a play queue, so this way you can rearrange the queue. While writing I realise that your Mac OS app (and probably the web player too) doesn't automatically play the next episode as on iOS. So I guess that's yet another feature request, but an option to reorder would still be useful without auto-play.

So just to sum up, here're my suggestions sorted by priority:

1. Newest episodes first
    –  This could be done with either sorting options or just a reverse-sorting-switch
2. Rearrange podcasts/episodes by dragging 
3. Option to auto-play next podcast on the list (goes well with the points above)
4. Playlists (synced with iOS or not)

I hope all this makes sense and that you want to and can implement (some of) these ideas :)

**Comment by nathanbirrell** [comment]
Unfortunately this really is just a simple unofficial webview wrapper, with some media key shortcuts for convenience. 

The features you've suggested would be something for the official Overcast webapp. They would be good for @marcoarment to take in to consideration. I'm hoping he has a macOS app or a web update on his radar. 👍

**Comment by maanemann** [comment]
Yeah that's what I thought, was just thinking that you might have plans about developing it further. But I can imagine that'd be difficult if not impossible when not having access to the official code. Let's indeed hope that @marcoarment is considering some of these ideas.

Thanks for making the third party app anyway, it's very useful despite being simple :)
