### ISSUE TITLE
Can't go back to main window

### ISSUE THREAD

**Issue by hylaride** [nathanbirrell/overcast-macos#9]
Hi!

I clicked on a link to go to a podcast's website and it opened it within the app.  I didn't immediately see the back button with command-[, so I exited the app.  The app now opens again at the website and I see no way of exiting and going back.

**Comment by Thistle98** [comment]
Found a fix for this. Delete the Overcast app, then go to finder and press (Cmd, Shift, G), then search for the folder (~/Library/Application Support/). Once in the folder search for the "Overcast" folder, delete the folder and then clear your trash bin. Then redownload the Overcast app and it should hopefully work.

**Comment by nathanbirrell** [comment]
Sorry this isn't being actively maintained at the moment, feel free to PR any fixes 😄
